//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int id { get; set; }
        public string Item_name { get; set; }
        public int Quntity { get; set; }
        public double Unit_price { get; set; }
        public double Total { get; set; }
        public double Net { get; set; }
    }
}
